model:
  model : Rnet # model and model_path need not be specified if using SSL. i
  model_path : null
  device  : cuda
  ssl : 
    encoder:
      encoder_type: SIMCLR
      encoder_path:  /content/models/SIMCLR_ssl.ckpt
      e_embedding_size: 2048
      e_lr: 1e-2
      train_encoder: False

    classifier:
      classifier_type: SSLEvaluator
      c_num_classes: 2
      c_hidden_dim: 64
      c_dropout: 0.1
      c_lr : 1e-6 
    
data:
  dataset : csv
  path : /home/ubuntu/t/Active-Labeler/sample.csv
train:
  optimizer :
    name : SGD
    config :
      momentum : 0
  loss_fn :
    name : BCELoss
  batch_size : 64
  epochs : 5
active_learner :
  iterations : 30
  strategy : uncertainty_sampling
  num_labelled : 50
  limit : -1
  preindex : False