model:
  model : Rnet
  model_path : null
  device  : cuda
data:
  dataset : csv
  path : /home/ubuntu/t/Active-Labeler/sample.csv
train:
  optimizer :
    name : SGD
    config :
      lr : 0.01
  loss_fn :
    name : BCELoss
  batch_size : 64
  epochs : 5
active_learner :
  iterations : 30
  strategy : uncertainty_sampling
  num_labelled : 50
  limit : -1
  