encoder:
  encoder_type: SIMCLR
  encoder_path:  /content/models/SIMCLR_ssl.ckpt
  e_embedding_size: 32
  e_lr: 1e-2
  train_encoder: False

classifier:
  classifier_type: SSLEvaluator
  c_num_classes: 2
  c_hidden_dim: 64
  c_linear_lr: 1e-1
  c_dropout: 0.1
  c_gamma: 0.1
  c_decay_epochs: [60, 80]
  c_weight_decay: 1e-6
  c_final_lr: 1e-6
  c_momentum: 0.9
  c_scheduler_type: cosine

miscellaneous:
  seed: 100
  cpus: 4
  device: cuda

training:
  epochs: 50
