encoder:
  encoder_type: SIMCLR
  encoder_path: PATH
  e_embedding_size: 512
  e_lr: 1e-2
  train_encoder: False

classifier:
  classifier_type: SSLEvaluator
  c_num_classes: 2
  c_hidden_dim: 128
  c_linear_lr: 1e-1
  c_dropout: 0.1
  c_gamma: 0.1
  c_decay_epochs: [60, 80]
  c_weight_decay: 1e-6
  c_final_lr: 1e-6
  c_momentum: 0.9
  c_scheduler_type: cosine # Help: cosine or step
  c_weights: None

miscellaneous:
  seed: 42
  cpus: 4
  device: cuda

training:
  epochs: 100
  